### ISSUE TITLE
Naming issues with deep queries

### ISSUE THREAD

**Issue by omstuhler** [vanatteveldt/rsyntax#15]
Hi,

firstly, thank you for providing this great package!

I have noticed that when I try to define some deeper queries and annotate a tokens object, I run into strange naming issues.

```R
##### Define tokens object
tokens = spacy_parse(c("Joe called and asked Jenny and Mike."), dependency=T)

##### Define query that doesn't work (should ideally markup "Mike")
example_query = tquery(token = "Joe",
                                 parents(
                                         children(
                                                  children(
                                                           children(pos = c("NOUN", "PROPN"),label = "T")
                                                  )
                                         )
                                 )
)
tokens = tokens %>%
  annotate_tqueries("example_query", example_query)
```
This throws me the following error:
```
Error in data.table::setcolorder(nodes, c(".ID", setdiff(colnames(nodes),  : 
  x has some duplicated column name(s): .DROP 1.y. Please remove or rename the duplicate(s) and try again.
In addition: Warning message:
In merge.data.table(selection, nested, by.x = c("doc_id", "sentence",  :
  column names '.DROP 1.y' are duplicated in the result
```
I have tried to investigate this problem by iteratively eliminating single aspects of the query. Generally, I found that the error only occurs when there is a match in the tokens object  (e.g. annotating on a tokens object created by ```spacy_parse(c("Joe called."), dependency=T, tag = T)``` with the above query would not throw the error. As does eliminating ```"PROPN"``` from the query.). Still, I can't quite make sense of this. Sorry for the bulky reproduction example - but this seems to mostly occur with bulky queries.

**Comment by kasperwelbers** [comment]
Hi @omstuhler,

Thanks for reporting this! It turned out to be a problem we already solved at some point, but the solution itself broke and this wasn't caught in a unit test. I've now fixed it in the dev version, and will also submit an update to CRAN in a minute (was about time anyway)

Although it might not be very interesting, I'll briefly describe the problem since you already looked into it. You wouldn't have been able to make sense of this without staring deeply into the code.  For deep nested searches, the retrieved nodes and their retrieved children (or parents) are recursively merged together. Nodes to which no label is assigned can be dropped after passing over them, so they are temporarily stored in  a .DROP column. But at some point we ran into the issue that we needed to keep track of multiple temporary nodes, and the most efficient way to do that in the current design is indexed columns (.DROP 1, .DROP 2, etc. It's not pretty, but in data.table it's efficient). Long story short, we didn't properly update a certain part of the code to remove the indexed .DROP columns, and this breaks with consecutive nested layers, because you'd get duplicate column names.
