### ISSUE TITLE
plot_tree - positioning edge label on edge instead of node

### ISSUE THREAD

**Issue by omstuhler** [vanatteveldt/rsyntax#17]
Sorry I keep adding to the wish list.

Would it be possible at all to add an option in ```plot_tree``` to position the label of an edge on the edge, instead of on the child node? I read what you wrote on this on pp. 5-6 in Welbers et al. and I get that it might create a mess (especially in more complex sentences). However, for illustrative purposes, it might be confusing to find nodes, rather than edges labeled. I suspect you had the same thought when creating Fig. 1 on page 5.

Alternatively, is the code you used for Figure 1 available somewhere?

**Comment by kasperwelbers** [comment]
It's not a problem to add it, but the mess is real I'm afraid. plot_tree uses igraph for visualizing the network (but with a lot of tweaks), and edge labels can get lost behind nodes. I've added a parameter to the dev version on GitHub, but in many sentences it won't be useful (so I'll probably won't release it). See example below.

Figure 1 is mostly just an igraph plot with a tree layout, because the purpose of fig 1 was indeed to show that a dependency graph is just a directed acyclic graph. I can't find the specific code, but the idea was something like this.

```
library(rsyntax)

tokens = tokens_spacy[tokens_spacy$doc_id == 'text3',]
p = plot_tree(tokens, rel_on_edge = T)   ## rel_on_edge is the arg for edge labels

library(igraph)
p$label = paste(p$token_id, p$lemma, sep='\n')

nodes = data.frame(id=p$token_id, label= paste(p$token_id, p$lemma, p$pos, sep='\n'))
edges = data.frame(from = match(p$parent, p$token_id),
                   to = p$token_id,
                   label = p$relation)
edges=edges[!is.na(edges$from),]

g = graph_from_data_frame(edges, vertices=nodes)

par(mar=c(0,0,0,0))
plot(g, layout=layout_as_tree, 
     vertex.shape='rectangle', vertex.size=35, vertex.size2=35, 
     edge.arrow.size=0)
```

The issue remains that a network like this tends to need some tweaking with Igraph to display nicely without overlapping or hidden text. So while I agree that it can be nice in a paper to explain what a dependency graph is, I probably won't include it in the package.
