### ISSUE TITLE
Error in fill && !is.na(label) : invalid 'x' type in 'x && y'

### ISSUE THREAD

**Issue by turbanisch** [vanatteveldt/rsyntax#20]
In the following example, I would like to have different matches for each entity of type person (and their child nodes that are not connected via a conjunction). I was playing around with different fill specifications to achieve this but essentially all of them produced the error message `Error in fill && !is.na(label): invalid 'x' type in 'x && y'`. What am I doing wrong?

``` r
library(spacyr)
library(rsyntax)

spacy_initialize(model = "en_core_web_md")
#> Found 'spacy_condaenv'. spacyr will use this environment
#> successfully initialized (spaCy Version: 3.0.5, language model: en_core_web_md)
#> (python options: type = "condaenv", value = "spacy_condaenv")

# define text to query
tokens = spacy_parse("Harris talked to President Biden and Mr. Fauci.", dependency = TRUE)
tokens = as_tokenindex(tokens)

# custom fill yields error message 
query <- tquery(label = "person", entity = "PERSON*", fill = custom_fill(BREAK(relation = "conj")))
#> Error in fill && !is.na(label): invalid 'x' type in 'x && y'

annotate_tqueries(tokens, "clause", query)
#> Error in annotate_tqueries(tokens, "clause", query): object 'query' not found
```

<sup>Created on 2021-09-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kasperwelbers** [comment]
Hi @turbanisch,

Again sorry for the delayed reply. The problem here is that custom_fill should be an unnamed argument (similar to how children() is nested in the tquery). It should not be passed to the 'fill' argument, which is a boolean argument for whether fill should be applied or not.

In other words, use:
`query <- tquery(label = "person", entity = "PERSON*", custom_fill(BREAK(relation = "conj")))`

Let me know if this does not resolve the problem!
