### ISSUE TITLE
plot_tree() and knit 

### ISSUE THREAD

**Issue by MarianoRico** [vanatteveldt/rsyntax#23]
Hi,

I am using your  ´plot_tree´ function from a Rmd document, using knit from Rstudio (pdf output). 
Unfortunately I cannot render the plot, despite I have tried with  ´viewer_mode =FALSE´ and other options.
Any clue?
Perhaps this is related to the missing figures in your html documentation (https://cran.r-project.org/web/packages/rsyntax/readme/README.html).   

Best regards,

-Mariano

**Comment by kasperwelbers** [comment]
Hi @MarianoRico,

Sorry for the late reply. Was at a conference last week.

I looked into the issue, and it turned out to be pretty weird. Long story short, I at some point need to have an empty plot to calculate things like string width. Since the plotting device isn't always open, I had to rely on a trycatch to see if a device was open, and if not create a new plot. Somehow, this had a sideeffect in rmarkdown (but really no clue why).

In any case, I wanted to look into making plot_tree more rmarkdown compatible at some point anyway. The reason this isn't straightforward is that it was initially designed to work with the viewer, because this allowed scrolling (which is often needed for large trees). 

I now updated the function so that viewer_mode = FALSE should work better with Rmarkdown. Please let me know if this solves the issue.

**Comment by kasperwelbers** [comment]
The update has now also been pushed to CRAN. So the idea would then indeed be that `viewer_mode = F` should be used to render the plot inside RMarkdown. This works for the devices where I tried it. If it doesn't work for you, please let me know by reopening the issue.
