### ISSUE TITLE
How is query_id selected?

### ISSUE THREAD

**Issue by omstuhler** [vanatteveldt/rsyntax#24]
I have been struggling to understand how `query_id` is chosen when annotating tqueries with multiple labels. I provide a minimal example below.

In the example below, the `query_id` is set to text1.1.2 - so the last digit corresponds to the `token_id` of the second label.

```R
  tokens_df = spacy_parse("John asked Jane", dependency = T)
  rule = tquery(token = "Jane", label = "OBJECT", fill = F,
                parents(label = "ACTION", fill = F,
                        ,children()                            
                )
  )
  annotate_tqueries(tokens_df, "query", rule, overwrite = T, copy = F)

   doc_id sentence token_id token lemma   pos parent relation   entity  query  query_id query_fill
1:  text1        1        1  John  John PROPN      2    nsubj PERSON_B   <NA>      <NA>         NA
2:  text1        1        2 asked   ask  VERB     NA     ROOT          ACTION text1.1.2          0
3:  text1        1        3  Jane  Jane PROPN      2     dobj PERSON_B OBJECT text1.1.2          0
```
However, when I exclude the additional `children()` line, the `token_id` becomes text1.1.3 - the last digit now corresponding to the `token_id` of the first label.

```R
  rule = tquery(token = "Jane", label = "OBJECT", fill = F,
                parents(label = "ACTION", fill = F
                #        ,children()                removed 
                )
  )
  annotate_tqueries(tokens_df, "query", rule, overwrite = T, copy = F)

   doc_id sentence token_id token lemma   pos parent relation   entity  query  query_id query_fill
1:  text1        1        1  John  John PROPN      2    nsubj PERSON_B   <NA>      <NA>         NA
2:  text1        1        2 asked   ask  VERB     NA     ROOT          ACTION text1.1.3          0
3:  text1        1        3  Jane  Jane PROPN      2     dobj PERSON_B OBJECT text1.1.3          0
```

For context: I'm making use of query annotations with `cast_text`and would then like to match casted text to specific tokens in the `tokens_df` - but this is currently not possible as the selection of `query_id` seems a little unpredictable. Though presumably it is predictable and I just haven't figured out the logic.

 I use the `en_core_web_sm` engine. Relevant session info printed below.

```R
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.0.1

other attached packages:
[1] rsyntax_0.1.3 spacyr_1.2.1 
```

**Comment by kasperwelbers** [comment]
Hi @omstuhler,

Interesting point. I hadn't yet considered a case where you might want to decompose the unique id back into the doc_id, sentence and token_id. The core criterion was that it should be unique, so I picked the first labeled node. However, the 'first' labeled node in this case refers to how the labeled nodes are organized internally, which is predictable, but not at all intuitive.

So I made a small change so that it now always picks the first label in a tquery (using the order of nodes specified by the user). This is probably most intuitive and flexible. For example:

```
tokens_df = spacy_parse("John asked Jane", dependency = T)

## first label is OBJECT, so this sets the ID token
rule = tquery(token = "Jane", label = "OBJECT", fill = F,
              parents(label = "ACTION", fill = F))
annotate_tqueries(tokens_df, "query", rule, overwrite = T, copy = F)

## first label is ACTION, so this sets the ID token
rule = tquery(label='ACTION', fill=F,
              children(label='OBJECT', token='Jane', fill=F))
annotate_tqueries(tokens_df, "query", rule, overwrite = T, copy = F)
```

Would that work?

**Comment by omstuhler** [comment]
Really appreciate the fast response! 

Just to be clear, by the 'first' labeled node you don't necessarily mean _the first element in the tquery_, is that right? I assume so because if that were the case, shouldn't it be `"text1.1.3"` in both my examples. On the other hand, if it were _the first labeled node that appears in the sentence_ then it should be `"text1.1.2"`. So what does first mean in this context? Or do you mean that 'first' depends on the inner logic of your code but is independent of both _token order in sentence_ and _node order in tquery_?

**Comment by kasperwelbers** [comment]
Oh, I meant that I just changed it. It used to be that internally it was independent of token/node order. So I changed that to 'the first element in the tquery'. That means it should now be 1.1.3 in both your cases.

If you need it now, you can install the dev version. I also submitted an update to CRAN a few minutes ago (because I had some pending updates anyway), so it should be there in a few days or so.

**Comment by omstuhler** [comment]
Oh, amazing, so quick. I really appreciate it! One could think about adding a parameter for which node should be marked up in the future. But only if it's very simple. Your change should solve all my immediate problems.

**Comment by kasperwelbers** [comment]
Yeah, I was thinking about that, but figured I should first see whether there are use cases before implementing a feature. While it's pretty simple to implement, it does add to the complexity for the user (due to having more arguments). 

So if you run into any use cases, you can re-open this issue. And thanks for signalling this!
