### ISSUE TITLE
Slight disparities when using on UDPipe data

### ISSUE THREAD

**Issue by gloignon** [vanatteveldt/rsyntax#6]
Here are the current differences between the data.table produced with udpipe_tokenindex and the one that comes out of the standard udpipe command.

- Some column names are different.
- Several columns are factors with udpipe_tokenindex, are normally int or chr with udpipe. This could become a problem with large data sets.
- The "relations" column in udpipe_tokenindex (dep_rel with udpipe) uses the word ROOT in caps while udpipe uses root, no caps.
- The "parent" column in udpipe_tokenindex (head_token_id with udpipe) uses NA when there is no parent, udpipe uses 0.

The following code should do the conversion, assuming that the output from udpipe() is a data.table:

```
tokens.fixed <- myUdPipeResult[!grepl("-", token_id, fixed=TRUE), .(
  doc_id ,
  sentence = sentence_id,
  token_id = as.numeric(token_id),
  token = as.factor(token),
  lemma = as.factor(lemma),
  POS = as.factor(upos),
  xpos = as.factor(xpos),
  feats = as.factor(feats),
  parent = as.numeric(head_token_id),
  relation = as.factor(dep_rel),
  deps = as.factor(deps)
)]
tokens.fixed[relation == "root", relation := "ROOT"]
tokens.fixed[parent == 0, parent := NA]
```

Do note that, when using the annotate function, the "POS" variable now needs to be in lower case. Example:

```
­> tokens.fixed %>%
+   annotate("clauses", d=direct, x=xcomp)
Error in lookup_tokens(tokens, lookup, use_index = use_index) : 
  pos is not a valid column name in tokens
```

To circumvent that, I duplicated the column, one as POS and one as pos. It works, but causes other problems. For instance, the plot_tree function now displays both the POS and pos variable under the lemmas:

![image](https://user-images.githubusercontent.com/12416756/70806632-c3261780-1d89-11ea-8f20-6ce46b3f4631.png)

That part of the problem I can fix by specifying that I want the pos variable in the function call as such:

```
tokens.fixed %>%
  annotate("clauses", d = direct, x = xcomp, block_fill = T) %>%
  plot_tree(annotation = "clauses", pos)
```

**Comment by kasperwelbers** [comment]
We indeed change some columns and how NAs are dealt with in order to work with the udpipe data. Different parsers (e.g., udpipe, spacy, corenlp) use different conventions, so this is intentional.

Though not all columns need to be standardized. POS, for instance, is free to have any name. As long as it's consistent with how POS is used in the tqueries. So in your case, the tqueries for 'direct' and 'xcomp' use lowercase pos. Did you get these queries from the tutorial? because in that case they've been designed for spacy output. 

It's not only naming conventions of column in different parsers. There are also some differences in actual POS tag and dependency relation labels (not every parser is fully UD compliant). Once we finalize rsyntax for CRAN, it's probably best to keep the syntax rules in a separate github. Like a cookbook for different languages / parsers.
