### ISSUE TITLE
Inconsistent base text size in plot_tree graph

### ISSUE THREAD

**Issue by gloignon** [vanatteveldt/rsyntax#7]
I don't know if it is intended behavior, but the base text size is smaller when not specifying which variables to add to the graph. Example:

```
tokens.fixed[, ] %>%
  annotate("clauses", d = direct, x = xcomp, block_fill = T) %>%
  plot_tree(annotation = "clauses")
```

![image](https://user-images.githubusercontent.com/12416756/70806809-1f893700-1d8a-11ea-97bc-7f4977c56047.png)

```
tokens.fixed[, ] %>%
  annotate("clauses", d = direct, x = xcomp, block_fill = T) %>%
  plot_tree(annotation = "clauses", POS)
```
![image](https://user-images.githubusercontent.com/12416756/70806851-3760bb00-1d8a-11ea-98de-afe0b9887729.png)

**Comment by kasperwelbers** [comment]
Hmm, are you using the latest version? In a prior versions (quite some time ago, I think) we created the plots in the current plotting device, so it had to scale with the size of the plotting device. This was problematic with large trees that would indeed require scaling the text size. 

Now, however, it should be the case that trees are plotted directly to pdf, and the pdf file is opened in the R(studio) viewer (through a silly HTML hack). On my device this prevents the scaling of text size.

Though off course, if you put your 2 plots side by side the upper one should have smaller text. If you include the very long 'feats' column, then text size needs to be very small in order to fit it on one line.

**Comment by gloignon** [comment]
Ok I tried including the "feats" column and indeed the text size got smaller.
