### ISSUE TITLE
Every other plot is blank (minor issue)

### ISSUE THREAD

**Issue by gloignon** [vanatteveldt/rsyntax#8]
Not a show stopper at all, but on my machine every other plot produced by plot_tree is blank. I just go back and delete the empty plots in RStudio, not a big deal.

**Comment by gloignon** [comment]
Btw, congrats on pushing the package to CRAN! :)

**Comment by gloignon** [comment]
Ok in the new version that got pushed today, the actual plot appears in the viewer, and a blank plot is added in the plots pane. Producing another plot will overwrite the one in the viewer, etc.

**Comment by kasperwelbers** [comment]
Good point. The reason that before it produced a white plot between plots is that in order to properly use the space in the plotting device I had to make an empty plot first to get the plot device sizes.

I actually didn't know that with the new approach empty plots are still created, and it might actually not be necessary so I'll look into that. The new approach is to create a pdf file (by default in temp, but you can also save it elsewhere) and embed this in an HTML file that can be shown and scrolled in the viewer. This should solve the issue of not being able to read the text in larger trees.
