### ISSUE TITLE
Word floating in plot? (with possible solution)

### ISSUE THREAD

**Issue by gloignon** [vanatteveldt/rsyntax#9]
I will sometimes get an issue where a mysterious floating word appears in the plot. It is a word from the sentence that is floating by itself. This happens when the parser replaces word (e.g. in French _des_ is parsed as _de les_, that is standard parsing). 

I don't know if that counts as an issue or if it's just the script working as intended. Maybe it could simply emit a warning when this happens. I am posting this to document the problem (and a simple fix) in case it happens to somebody else.

```
finite.verb <-
  tquery(
    pos = c("VERB*"),
    NOT(relation = c("advcl", "acl")),
    children(NOT(relation = "aux*"), NOT(pos = "AUX")),
    label = "verbe fini"
  )

phrase <- "Puisque Luc est un chat, je lui ferai des oeufs."
mes.tokens <- udpipe_tokenindex(phrase, udpipe_model = "french-gsd")
mes.tokens$pos <- mes.tokens$POS

mes.tokens %>%
  annotate('VP', finite.verb, fill = FALSE) %>%
  plot_tree(annotation = 'VP', token, lemma, POS)
```
Resulting plot:
![image](https://user-images.githubusercontent.com/12416756/72989560-7c7e0100-3dbc-11ea-8895-77f8bd035444.png)

Looking at the table, that _des_ is indeed present:

![image](https://user-images.githubusercontent.com/12416756/72989606-97e90c00-3dbc-11ea-98e0-7145fc640aa7.png)

**Possible fix:** I just filter out the words that have no POS, problem fixed. Removing the ROOT relation from the word will not do the trick (you would just get a floating work with no relation).

**Comment by kasperwelbers** [comment]
Ah, it seems that the model for French sometimes finds multiple roots in one sentence. Though the fact that the "des" root doesn't have a POS tag might indicate that the parser messes up here.

The reason that des is shown floating to the right is actually due to an intended behaviour. plot_tree is supposed to visualize one sentence, and if there are multiple roots (i.e. separate trees) then these are shown side by side. 

The reason that the "des" root is shown on the right side, is that if there are multiple roots, they are plotted side by side to make this easier to see. Also, it makes sense from a dependency tree perspective to consider the text in different roots as separate.

The reason we implemented this is actually because we're working on some ways to simplify trees. The idea is then that we cut complicated trees into multiple parts, so that we can use less complicated queries to extract clauses. The basic tools are already in rsyntax, but the implementation is not quite there yet.
